<!DOCTYPE html>
<html>
<head>
	<title>User</title>
</head>
<body>
		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h2>Pelatihan Learning Vector Quantization 3</h2>
					</div>
					<div class="panel-body" style="display: block;">
						<div class="col-md-12">
  					<div class="content-box-large">
		  			
		  				<div class="panel-body">
		  					<h3 >Form Pelatihan</h3>

		  					<form class="form-horizontal" role="form" method="post">
		  						<div class="form-group">
								    <label for="indeks" class="col-sm-2 control-label">Indeks Antropometri</label>
								    <div class="col-sm-10">
								      <select class="form-control" id="indeks" name="indeks">
													<option></option>
													<option value="beratbadan">BB/U</option>
													<option value="tinggibadan">TB/U</option>
									</select> 
								    </div>
								  </div>
				            
										<div class="form-group">
								    <label for="bagidata" class="col-sm-2 control-label">Pembagian Data Latih dan Data Uji</label>
								    <div class="col-sm-10">
								      <select class="form-control" id="bagidata" name="pembagian">
													<option></option>
													<option value="90">Pembagian 90:10</option>
													<option value="80">Pembagian 80:20</option>
									</select> 
								    </div>
								  </div>

								  <div class="form-group">
								    <label class="col-sm-2 control-label">Epoch</label>
								    <div class="col-sm-10">
								      <span class="form-control">1000</span>
								    </div>
								  </div>
								  <div class="form-group">
								    <label for="learningrate" class="col-sm-2 control-label">Learning Rate</label>
								    <div class="col-sm-10">
								      <select class="form-control" id="learningrate" name="learning_rate">
													<option></option>
													<!-- <option value="0.015">0.015</option> -->
													<option value="0.025">0.025</option>
													<option value="0.075">0.075</option>
													<option value="0.175">0.175</option>
													<option value="0.3">0.3</option>
													<!-- <option value="0.1">0.1</option>
													<option value="0.125">0.125</option>
													<option value="0.15">0.15</option>
													<option value="0.2">0.2</option>
													<option value="0.05">0.05</option>
													<option value="0.225">0.225</option>
													<option value="0.25">0.25</option>
													<option value="0.275">0.275</option>
													<option value="0.4">0.4</option>
													<option value="0.5">0.5</option>
													<option value="0.6">0.6</option>
													<option value="0.035">0.035</option>
													<option value="0.045">0.045</option>
													<option value="0.055">0.055</option>
													<option value="0.065">0.065</option>
													<option value="0.085">0.085</option>
													<option value="0.095">0.095</option>
													<option value="0.01">0.01</option>
													<option value="0.02">0.02</option>
													<option value="0.03">0.03</option>
													<option value="0.04">0.04</option>
													<option value="0.06">0.06</option>
													<option value="0.07">0.07</option>
													<option value="0.08">0.08</option>
													<option value="0.09">0.09</option> -->

									</select> 
								    </div>
								  </div>
								 
								  <div class="form-group">
								    <label class="col-sm-2 control-label">Minimum Learning Rate</label>
								    <div class="col-sm-10">
								      <span class="form-control">0.02</span>
								    </div>
								  </div>

								  <div class="form-group">
								    <label for="window" class="col-sm-2 control-label">Window</label>
								    <div class="col-sm-10">
								      <select class="form-control" id="window" name="window">
													<option></option>
													<!-- <option value="0.1">0.1</option> -->
													<option value="0.2">0.2</option>
													<option value="0.3">0.3</option>
													<option value="0.4">0.4</option>
													<!-- <option value="0.5">0.5</option>
													<option value="0.6">0.6</option>
													<option value="0.7">0.7</option>
													<option value="0.8">0.8</option>
													<option value="0.9">0.9</option> -->
									</select> 
								    </div>
								  </div>

								  <div class="form-group">
								    <label class="col-sm-2 control-label">Pengurangan Learning Rate</label>
								    <div class="col-sm-10">
								      <span class="form-control">0.01</span>
								    </div>
								  </div>

								  <div class="form-group">
								    <div class="col-sm-offset-2 col-sm-10">
								      <button type="submit" class="btn btn-primary">Proses</button>
								    </div>
								  </div>
								</form>
		  				</div>
		  			</div>
  				</div>
					</div>
				</div>
			</div>
		</div><!--/.row-->
</html>
