
<div class="row">
	<div class="col-md-12">
				<div class="box box-default box-solid" style="text-align: center;">
					<h2>Selamat Datang di Sistem Penerapan LVQ 3 dalam Klasifikasi Status Gizi Balita</h2>
            <!-- /.box-header -->
            		<div class="panel-body" style="display: block;">
						<p><img src="img/uin.jpg" width="200px"></p>
					</div>
            <!-- /.box-body -->
          		</div>
			</div>
</div>

		<div class="row">
			<div class="col-sm-12">
				<div class="box box-success box-solid">
            		<div class="box-header with-border">
              		<h3 class="box-title">Metode LVQ 3</h3>
              		<div class="box-tools pull-right">
                		<button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                		</button>
              		</div>
              <!-- /.box-tools -->
            		</div>
            <!-- /.box-header -->
            		<div class="box-body">
              			<p>
                    LVQ 3 merupakan algoritma pengembangan dari metode LVQ. Perbedaan metode LVQ dan LVQ 3 yaitu pada proses (training) pelatihan LVQ dipengaruhi beberapa parameter seperti: nilai learning rate (α),  nilai minimal learning rate (Mina), pengurangan nilai learning rate, sedangkan pada metode LVQ 3 selain parameter pada LVQ juga dibutuhkan parameter window (ε) (Budianita dan Prijodiprodjo, 2013).   
                    </p>
            		</div>
            <!-- /.box-body -->
          		</div>
			</div>
			</div>

      <div class="row">
      <div class="col-sm-12">
        <div class="box box-warning box-solid">
                <div class="box-header with-border">
                  <h3 class="box-title">Status Gizi</h3>
                  <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                  </div>
              <!-- /.box-tools -->
                </div>
            <!-- /.box-header -->
                <div class="box-body">
                      <p>
                        Status gizi atau (nutritional status) adalah keadaan menyeimbangkan asupan zat gizi yang di dapat dari makanan dan kebutuhan pada zat gizi untuk tubuh.
                      </p>
                </div>
            <!-- /.box-body -->
              </div>
      </div>
      </div>

      <div class="row">
      <div class="col-sm-12">
        <div class="box box-info box-solid">
                <div class="box-header with-border">
                  <h3 class="box-title">Penilaian Status Gizi</h3>
                  <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                  </div>
              <!-- /.box-tools -->
                </div>
            <!-- /.box-header -->
                <div class="box-body">
                      <p>
                        Menurut (Supariasa et al., 2014) antropometri sebagai salah satu cara untuk menilai status gizi memliki keunggulan yaitu memiliki prosedur sederhana, hasil pengukuran tepat dan akurat, dapat mengevaluasi status gizi periode tertentu. Adapun indeks dalam melakukan penilaian status gizi metode antropometri diantaranya (Harjatmo et al., 2017):
                        <li>Indeks Panjang atau Tinggi menurut Umur (PB-TB/U)</li>
                        <li>Indeks Berat Badan menurut Umur (BB/U)</li>
                        <li>Indeks Berat Badan menurut Panjang atau Tinggi Badan (BB/PB-TB)</li>
                        <li>Indek Massa Tubuh menurut Umur (IMT/U)</li>
                      </p>
                </div>
            <!-- /.box-body -->
              </div>
      </div>
      </div>


      <div class="row">
      <div class="col-sm-12">
        <div class="box box-danger box-solid">
                <div class="box-header with-border">
                  <h3 class="box-title">Faktor yang Mempengaruhi Status Gizi</h3>
                  <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                  </div>
              <!-- /.box-tools -->
                </div>
            <!-- /.box-header -->
                <div class="box-body">
                      <p>
                        Faktor-faktor yang menentukan status gizi secara umum terdiri dari pendidikan orang tua, keadaan ekonomi (Nursalam, 2005) dalam (Purnamasari, Anggraeni, Wahyuni, dan Apriliana, 2014).
                      </p>
                      <p>
                        Beberapa faktor juga mempengaruhi status gizi yaitu konsumsi makanan yang tidak mencukupi kebutuhan sehingga tubuh kekurangan zat gizi, pemberian ASI, kondisi sosial ekonomi, faktor sosial keadaan penduduk, umur, jenis kelamin dan pelayanan kesehatan menurut Perry dan Potter (2005) dalam (Purnamasari et al., 2014)
                      </p>
                      <p>
                        Penelitian (Putri, Sulastri, dan Lestari, 2015) menghasilkan bahwa terdapat hubungan yang bermakna dengan status gizi balita yaitu pendidikan ibu, pekerjaan ibu, pendapatan keluarga, jumlah anak dan pola asuh ibu. Penelitian lain (Suryani, 2017) menghasilkan bahwa ada pengaruh antara pendidikan, jumlah anak, status ekonomi keluarga dan pengetahuan terhadap status gizi balita. 
                      </p>
                      <p>
                        Berdasarkan (Armini et al., 2017) faktor lain yang juga mempengaruhi status gizi yaitu melalui faktor panjang badan-tinggi badan perubahan tinggi badan relatif pelan, akibatnya sulit mengukur tinggi badan yang tepat. Oleh karena itu dibutuhkan dua macam teknik pengukuran, pada anak umur kurang dari 2 tahun dengan posisi tidur terlentang dan pada  anak lebih dari 2 tahun dengan posisi berdiri.
                      </p>
                      <p>
                         Faktor lain yang mempengaruhi status gizi berdasarkan penelitian (Fitriyah dan Mahmudiono, 2013) menghasilkan bahwa terdapat hubungan antara status gizi dengan konsumsi vitamin A. Karena vitamin A memiliki peran rendahnya resistensi terhadap infeksi. Semakin rendah konsumsi vitamin A, maka semakin menurun tingkat imunitas seseorang. 
                      </p>
                </div>
            <!-- /.box-body -->
              </div>
      </div>
      </div>