<!DOCTYPE html>
<html>
<head>
	<title>Edit User</title>
</head>
<body>

	<div class="row">    
		<div class="col-lg-12">        
			<div class="panel panel-default">            
				<div class="panel-body">                
					<div class="row center-block">
					<div class="content-box-large">
					<div class="panel-heading">
					<div class="panel-title">Edit Users</div>
					<div class="panel-body">
						<form action="" method="post">
							<input type="hidden" name="id_users" value="<?= $user->id_users ?>">
						<div class="form-group">
							<label>Nama</label>
							<input type="text" name="nama" value="<?= $user->nama ?>" class="form-control">
						</div>
						<div class="form-group">
							<label>Username</label>
							<input type="text" name="username" value="<?= $user->username ?>" class="form-control">
						</div>
						<div class="form-group">
							<label>Password</label>
							<input type="text" name="password" value="<?= $user->password ?>" class="form-control">
						</div>
						
						<button class="btn btn-success"><i class="glyphicon glyphicon-refresh"></i> Update</button>
						<button class="btn btn-danger">
						<a href="<?= $this->url->get('users/index/')?>" ><i class="glyphicon glyphicon-remove"></i> Batal</a>
						</button>
						</form>
					</div>
					</div>
					</div>
					</div>            
				</div>        
			</div>    
		</div>
	</div>

</body>
</html>