<!DOCTYPE html>
<html>
<head>
	<title>User</title>
</head>
<body>

	<div class="row">    
		<div class="col-lg-12">        
			<div class="panel panel-default">            
				<div class="panel-body">                
					<div class="row center-block">                        
					<div class="content-box-large">
					<div class="panel-heading">
						<div class="panel-title">Tambah Users</div>
					<div class="panel-body">
						<form action="" method="post">
							<div class="form-group">
								<label>Nama</label>
								<input type="text" name="nama" class="form-control">
							</div>
							<div class="form-group">
								<label>Username</label>
								<input type="text" name="username" class="form-control">
							</div>
							<div class="form-group">
								<label>Password</label>
								<input type="password" name="password" class="form-control">
							</div>
								<button class="btn btn-success"><i class="glyphicon glyphicon-plus"></i> Tambah </button>
								<button class="btn btn-danger">
									<a href="<?= $this->url->get('users/index/')?>" ><i class="glyphicon glyphicon-remove"></i>Batal</a>
								</button>

										
						</form>
					</div>
					</div>
					</div>
					</div>            
				</div>        
			</div>    
		</div>
	</div>

</body>
</html>