<!DOCTYPE html>
<html>
<head>
    <title>Tinggi Badan</title>
</head>
<body>
    <div class="row">    
        <div class="col-lg-12">        
            <div class="panel panel-default">
            <div class="panel-heading">
                <h1>Data Baru Balita</h1>
            </div>             
                <div class="panel-body" style="display: block;">                
                    <div class="col-md-12">       
                        <div class="content-box-large">
                        <div class="panel-header">
                        <div class="panel-title">
                        </div>
                        <div class="panel-body">
                            <a href="<?= $this->url->get('tinggibadan') ?>" class="btn btn-defaultactive"  style="color: white; background-color: #5bc0de;background-color: #5bc0de"><i class="glyphicon glyphicon-eye-open"></i> Data Tinggi Badan</a>
                            <a href="<?= $this->url->get('pengujian/createdatabarutb') ?>" class="btn btn-success"><i class="glyphicon glyphicon-plus"></i> Data Baru TB/U</a>
                            <a href="<?= $this->url->get('pengujian/normalisasidatabarutb') ?>" class="btn btn-default"><i class="glyphicon glyphicon-eye-open"></i> Normalisasi</a>
                            <a href="<?= $this->url->get('pengujian/indexujidatabarutb') ?>" class="btn btn-default"><i class="glyphicon glyphicon-eye-open"></i> Uji Data Baru</a>

                            <div class="table-responsive">
                                <table class="table table-bordered">
                                <thead>
                                    <tr class="success">
                                        <th>Id Balita</th>
                                        <th>Nama</th>
                                        <th>Jenis Kelamin</th>
                                        <th>Umur</th>
                                        <th>Tinggi Badan</th>
                                        <th>Cara Ukur</th>
                                        <th>Vitamin A</th>
                                        <th>Status Ekonomi</th>
                                        <th>Pendidikan Ibu</th>
                                        <th>Pekerjaan Ayah</th>
                                        <th>Status Gizi</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($tinggibadan as $tb): ?>
                                    <tr>
                                        <td><?= $tb->id_balita ?></td> 
                                        <td><?= $tb->nama ?></td>
                                        <td><?= $tb->jk ?></td> 
                                        <td><?= $tb->umur ?></td>
                                        <td><?= $tb->tinggi ?></td>
                                        <td><?= $tb->cr_ukur ?></td>
                                        <td><?= $tb->vit_a ?></td>
                                        <td><?= $tb->ekonomi ?></td>
                                        <td><?= $tb->pendidikan_ibu ?></td>
                                        <td><?= $tb->pekerjaan_ayah ?></td>
                                        <td><?= $tb->status_gizi ?></td>
                                        <td>
                                            <a href="<?= $this->url->get('pengujian/tbbaru_edit/'.$tb->id_balita) ?>" class="btn btn-info"><i class="glyphicon glyphicon-edit"></i></a>
                                            <a href="<?= $this->url->get('pengujian/deletetb/'.$tb->id_balita) ?>" class="btn btn-danger"> <i class="glyphicon glyphicon-trash"></i> </a>
                                        </td>
                                    </tr>   
                                    <?php endforeach ?>
                                </tbody>
                                </table>
                            </div>
                        </div>
                        </div>
                        </div>
                    </div>            
                </div>        
            </div>    
        </div>
    </div>

</body>
</html>