
		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h1>Pengujian LVQ 3</h1>
					</div>
					<div class="panel-body" style="display: block;">
						<div class="col-md-12">
  					<div class="content-box-large">
		  			
		  				<div class="panel-body">
		  					<form class="form-horizontal" role="form">
								<div class="form-group">
											<label class="col-md-2 control-label">Indeks Antropometri</label>
											<div class="col-md-10">
												<label class="radio radio-inline">
													<input type="radio">
													BB/U</label>
												<label class="radio radio-inline">
													<input type="radio">
													TB/U</label>
											</div>
										</div>

		  						<div class="form-group">
											<label class="col-md-2 control-label">Pembagian Data</label>
											<div class="col-md-10">
												<label class="radio radio-inline">
													<input type="radio">
													Data Uji 10% </label>
												<label class="radio radio-inline">
													<input type="radio">
													Data Uji 20% </label>
											</div>
										</div>
									
								  <div class="form-group">
								    <div class="col-sm-offset-3 col-sm-10">
								      <button type="submit" class="btn btn-primary">Proses</button>
								    </div>
								  </div>
								</form>

								<div class="form-group">
											<label>Proses Pengujian Klasifikasi Metode LVQ 3</label>
											
											<table class="table table-bordered">
					                            <thead>
					                                <tr class="success">
					                                    <th>Id Balita</th>
					                                    <th>Nama</th>
					                                    <th>Jenis Kelamin</th>
					                                    <th>Umur</th>
					                                    <th>Berat Badan</th>
					                                    <th>Cara Ukur</th>
					                                    <th>Vitamin A</th>
					                                    <th>Status Ekonomi</th>
					                                    <th>Pendidikan Ibu</th>
					                                    <th>Pekerjaan Ayah</th>
					                                    <th>Status Gizi</th>
					                                    <th>Hasil Uji</th>
					                                </tr>
					                            </thead>
					                            <tbody>
					                                <tr>
					                                    <td>-</td> 
					                                    <td>-</td>
					                                    <td>-</td> 
					                                    <td>-</td>
					                                    <td>-</td>
					                                    <td>-</td>
					                                    <td>-</td>
					                                    <td>-</td>
					                                    <td>-</td>
					                                    <td>-</td>
					                                    <td>-</td>
					                                    <td>Benar/Salah</td>
					                                </tr>   
					                            </tbody>
					                        </table>

								</div>

							<p>Proses Pengujian menghasilkan Akurasi sebesar ....%</p>
							
		  					
											 <!-- BAR CHART -->
				          <div class="box box-success">
				            <div class="box-header with-border">
				              <h3 class="box-title">Bar Chart</h3>

				              <div class="box-tools pull-right">
				                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
				                </button>
				                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
				              </div>
				            </div>
				            <div class="box-body">
				              <div class="chart">
				                <canvas id="barChart" style="height:230px"></canvas>
				              </div>
				            </div>
				            <!-- /.box-body -->
				          </div>

		  				</div>
		  			</div>
  				</div>
					</div>
				</div>
			</div>
		</div><!--/.row-->

<script>
  $(function () {
    /* ChartJS
     * -------
     * Here we will create a few charts using ChartJS
     */

    //--------------
    //- AREA CHART -
    //--------------

    // Get context with jQuery - using jQuery's .get() method.
    var areaChartCanvas = $('#areaChart').get(0).getContext('2d')
    // This will get the first returned node in the jQuery collection.
    var areaChart       = new Chart(areaChartCanvas)

    var areaChartData = {
      labels  : ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
      datasets: [
        {
          label               : 'Electronics',
          fillColor           : 'rgba(210, 214, 222, 1)',
          strokeColor         : 'rgba(210, 214, 222, 1)',
          pointColor          : 'rgba(210, 214, 222, 1)',
          pointStrokeColor    : '#c1c7d1',
          pointHighlightFill  : '#fff',
          pointHighlightStroke: 'rgba(220,220,220,1)',
          data                : [65, 59, 80, 81, 56, 55, 40]
        },
        {
          label               : 'Digital Goods',
          fillColor           : 'rgba(60,141,188,0.9)',
          strokeColor         : 'rgba(60,141,188,0.8)',
          pointColor          : '#3b8bba',
          pointStrokeColor    : 'rgba(60,141,188,1)',
          pointHighlightFill  : '#fff',
          pointHighlightStroke: 'rgba(60,141,188,1)',
          data                : [28, 48, 40, 19, 86, 27, 90]
        }
      ]
    }

    var areaChartOptions = {
      //Boolean - If we should show the scale at all
      showScale               : true,
      //Boolean - Whether grid lines are shown across the chart
      scaleShowGridLines      : false,
      //String - Colour of the grid lines
      scaleGridLineColor      : 'rgba(0,0,0,.05)',
      //Number - Width of the grid lines
      scaleGridLineWidth      : 1,
      //Boolean - Whether to show horizontal lines (except X axis)
      scaleShowHorizontalLines: true,
      //Boolean - Whether to show vertical lines (except Y axis)
      scaleShowVerticalLines  : true,
      //Boolean - Whether the line is curved between points
      bezierCurve             : true,
      //Number - Tension of the bezier curve between points
      bezierCurveTension      : 0.3,
      //Boolean - Whether to show a dot for each point
      pointDot                : false,
      //Number - Radius of each point dot in pixels
      pointDotRadius          : 4,
      //Number - Pixel width of point dot stroke
      pointDotStrokeWidth     : 1,
      //Number - amount extra to add to the radius to cater for hit detection outside the drawn point
      pointHitDetectionRadius : 20,
      //Boolean - Whether to show a stroke for datasets
      datasetStroke           : true,
      //Number - Pixel width of dataset stroke
      datasetStrokeWidth      : 2,
      //Boolean - Whether to fill the dataset with a color
      datasetFill             : true,
      //String - A legend template
      legendTemplate          : '<ul class="<%=name.toLowerCase()%>-legend"><% for (var i=0; i<datasets.length; i++){%><li><span style="background-color:<%=datasets[i].lineColor%>"></span><%if(datasets[i].label){%><%=datasets[i].label%><%}%></li><%}%></ul>',
      //Boolean - whether to maintain the starting aspect ratio or not when responsive, if set to false, will take up entire container
      maintainAspectRatio     : true,
      //Boolean - whether to make the chart responsive to window resizing
      responsive              : true
    }

    //Create the line chart
    areaChart.Line(areaChartData, areaChartOptions)

    //-------------
    //- BAR CHART -
    //-------------
    var barChartCanvas                   = $('#barChart').get(0).getContext('2d')
    var barChart                         = new Chart(barChartCanvas)
    var barChartData                     = areaChartData
    barChartData.datasets[1].fillColor   = '#00a65a'
    barChartData.datasets[1].strokeColor = '#00a65a'
    barChartData.datasets[1].pointColor  = '#00a65a'
    var barChartOptions                  = {
      //Boolean - Whether the scale should start at zero, or an order of magnitude down from the lowest value
      scaleBeginAtZero        : true,
      //Boolean - Whether grid lines are shown across the chart
      scaleShowGridLines      : true,
      //String - Colour of the grid lines
      scaleGridLineColor      : 'rgba(0,0,0,.05)',
      //Number - Width of the grid lines
      scaleGridLineWidth      : 1,
      //Boolean - Whether to show horizontal lines (except X axis)
      scaleShowHorizontalLines: true,
      //Boolean - Whether to show vertical lines (except Y axis)
      scaleShowVerticalLines  : true,
      //Boolean - If there is a stroke on each bar
      barShowStroke           : true,
      //Number - Pixel width of the bar stroke
      barStrokeWidth          : 2,
      //Number - Spacing between each of the X value sets
      barValueSpacing         : 5,
      //Number - Spacing between data sets within X values
      barDatasetSpacing       : 1,
      //String - A legend template
      legendTemplate          : '<ul class="<%=name.toLowerCase()%>-legend"><% for (var i=0; i<datasets.length; i++){%><li><span style="background-color:<%=datasets[i].fillColor%>"></span><%if(datasets[i].label){%><%=datasets[i].label%><%}%></li><%}%></ul>',
      //Boolean - whether to make the chart responsive
      responsive              : true,
      maintainAspectRatio     : true
    }

    barChartOptions.datasetFill = false
    barChart.Bar(barChartData, barChartOptions)
  })
</script>
