<!DOCTYPE html>
<html>
<head>
	<title>User</title>
</head>
<body>
		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h2>Pengujian Learning Vector Quantization 3</h2>
					</div>
					<div class="panel-body" style="display: block;">
						<div class="col-md-12">
  					<div class="content-box-large">
		  			
		  				<div class="panel-body">
		  					<h3 >Form Pengujian Data Baru BB/U</h3>
		  					<form class="form-horizontal" role="form" method="post">
		  						<div class="form-group">
								    <label for="bagidata" class="col-sm-2 control-label">Pembagian Data Latih dan Data Uji</label>
								    <div class="col-sm-10">
								      <select class="form-control" id="bagidata" name="pembagian">
													<option></option>
													<option value="90">Pembagian 90:10</option>
													<option value="80">Pembagian 80:20</option>
									</select> 
								    </div>
								  </div>

								  <div class="form-group">
								    <label class="col-sm-2 control-label">Epoch</label>
								    <div class="col-sm-10">
								      <span class="form-control">1</span>
								    </div>
								  </div>
								  <div class="form-group">
								    <label for="learningrate" class="col-sm-2 control-label">Learning Rate</label>
								    <div class="col-sm-10">
								      	<select class="form-control" id="learningrate" name="learning_rate">
											<option></option>
											<option value="0.025">0.025</option>
											<option value="0.075">0.075</option>
											<option value="0.175">0.175</option>
											<option value="0.3">0.3</option>
											<!-- <option value="0.05">0.05</option>
											<option value="0.1">0.1</option>
											<option value="0.125">0.125</option>
											<option value="0.15">0.15</option>
											<option value="0.2">0.2</option>
											<option value="0.225">0.225</option>
											<option value="0.25">0.25</option>
											<option value="0.275">0.275</option> -->
										</select> 
								    </div>
								  </div>
								 
								  <div class="form-group">
								    <label class="col-sm-2 control-label">Minimum Learning Rate</label>
								    <div class="col-sm-10">
								      <span class="form-control">0.02</span>
								    </div>
								  </div>

								  <div class="form-group">
								    <label for="window" class="col-sm-2 control-label">Window</label>
								    <div class="col-sm-10">
								      <select class="form-control" id="window" name="window">
										<option></option>
										<option value="0.2">0.2</option>
										<option value="0.3">0.3</option>
										<option value="0.4">0.4</option>
									</select> 
								    </div>
								  </div>

								  <div class="form-group">
								    <label class="col-sm-2 control-label">Pengurangan Learning Rate</label>
								    <div class="col-sm-10">
								      <span class="form-control">0.01</span>
								    </div>
								  </div>

								  <div class="form-group">
								    <div class="col-sm-offset-2 col-sm-10">
								      <button type="submit" class="btn btn-primary">Proses</button>
								    </div>
								  </div>
							</form>

		  				</div>
		  			</div>
  				</div>
					</div>
				</div>
			</div>
		</div><!--/.row-->
</html>





    