<!DOCTYPE html>
<html>
<head>
    <title>Tinggi Badan</title>
</head>
<body>
    <div class="row">    
        <div class="col-lg-12">        
            <div class="panel panel-default">            
                <div class="panel-heading">
                    <h1>Data Baru Normalisasi </h1>
                </div>             
                <div class="panel-body" style="display: block;">                
                    <div class="col-md-12">
                        <div class="content-box-large">
                        <div class="panel-header">
                        <div class="panel-title">
                        </div>
                        
                        <div class="panel-body">
                            <a href="<?= $this->url->get('tinggibadan') ?>" class="btn btn-defaultactive"  style="color: white; background-color: #5bc0de;background-color: #5bc0de"><i class="glyphicon glyphicon-eye-open"></i> Data Tinggi Badan</a>
                            <a href="<?= $this->url->get('pengujian/databarutb') ?>" class="btn btn-success"><i class="glyphicon glyphicon-eye-open"></i></i> Data Baru TB/U</a>
                            <a href="<?= $this->url->get('pengujian/tahapnormalisasidatabarutb') ?>" class="btn btn-warning"><i class="glyphicon glyphicon-refresh"></i> Proses Normalisasi</a>
                            <a href="<?= $this->url->get('pengujian/indexujidatabarutb') ?>" class="btn btn-default"><i class="glyphicon glyphicon-eye-open"></i> Uji Data Baru</a>
                            
                            <div class="table-responsive">
                            <table class="table table-bordered">
                            <thead>
                                <tr class="success">
                                    <th>No</th>
                                    <th>Id Balita</th>
                                    <th>X1</th>
                                    <th>X2</th>
                                    <th>X3</th>
                                    <th>X4</th>
                                    <th>X5</th>
                                    <th>X6</th>
                                    <th>X7</th>
                                    <th>X8</th>
                                    <th>Status Gizi</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php 
                                    $no = 1;
                                    foreach ($tinggibadan as $tb): 
                                ?>
                                <tr>
                                    <td><?= $no ?></td> 
                                    <td><?= $tb->id_balita ?></td> 
                                    <td><?= $tb->x1 ?></td> 
                                    <td><?= $tb->x2 ?></td>
                                    <td><?= $tb->x3 ?></td>
                                    <td><?= $tb->x4 ?></td>
                                    <td><?= $tb->x5 ?></td>
                                    <td><?= $tb->x6 ?></td>
                                    <td><?= $tb->x7 ?></td>
                                    <td><?= $tb->x8 ?></td>
                                    <td><?= $tb->target ?></td>
                                    
                                </tr>   
                                <?php 
                                    $no++;
                                    endforeach 
                                ?>
                            </tbody>
                            </table>
                            </div>
                        </div>
                        </div>
                        </div>
                    </div>            
                </div>        
            </div>    
        </div>
    </div>

</body>
</html>